name: Terraform Dev Test

on:
  push:
    paths:
      - "envs/dev/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/dev

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
